core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("message.urls")),
    path('admin/', admin.site.urls),
]

message/urls.py
from django.urls import path
from .views import dashboard, profile_list, profile


app_name = "message"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
]

message/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models. Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    seguidores = models.ManyToManyField(
        "self",
        related_name="seguido_por",
        symmetrical=False,
        blank=True,
    )

    def __str__(self):
        return self.usuario.username

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(usuario=instance)
        user_profile.save()
        """
        A propriedade set precisa de iteravel e precisamos acessar o id
        para que o usuário "se siga" e possa ver suas próprias mensagens
        """
        user_profile.seguidores.add(instance.profile)
        user_profile.save()


class Mensagem(models.Model):
    user = models.ForeignKey(
        User,
        related_name="mensagens",
        on_delete=models.DO_NOTHING,
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "mensagens"

    def __str__(self) -> str:
        return (
            f"{self.user} "
            f"({self.created_at:%d/%m/%Y %H:%M}): "
            f"{self.body[:30]}..."
        )

message/forms.py
from email.message import Message
from socket import fromshare
from django import forms
from .models import Mensagem


class MessageForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Digite algo...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )


    class Meta:
        model = Mensagem
        exclude = ("user",)

message/views.py
from django.shortcuts import render, redirect
from .models import Profile, Mensagem
from .forms import MessageForm


def dashboard(request):
    # preenche o form com os dados que chegaram do request.POST
    form = MessageForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            mensagem = form.save(commit=False)
            mensagem.user = request.user
            mensagem.save()

            return redirect("message:dashboard")

    followed_messages = Mensagem.objects.filter(
        user__profile__in=request.user.profile.seguidores.all()
    ).order_by('-created_at')
    return render(
        request,
        "message/dashboard.html",
        {
            "form": form,
            "mensagens": followed_messages,
        }
    )

def profile_list(request):
    profiles = Profile.objects.exclude(usuario=request.user)
    return render(
        request,
        "message/profile_list.html",
        {
            "profiles": profiles,
        }
    )

def profile(request, pk):
    # Verifica se o objeto NÂO tem o atributo
    if not hasattr(request.user, "profile"):
        missing_profile = Profile(usuario=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.seguidores.add(profile)
        elif action == "unfollow":
            current_user_profile.seguidores.remove(profile)
        current_user_profile.save()

    return render(
        request,
        "message/profile.html",
        {
            "profile": profile,
        }
    )

message/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Mensagens curtas</title>
</head>
<body>
    <section class="hero is-small is-success mb-4">
        <div class="hero-body">
            <a href="{% url 'message:dashboard' %}">
                <h1 class="title is-1">Mensagens Curtas</h1>
            </a>
            <p class="subtitle is-4">Uma rede mensagens rápidas</p>
        </div>
    </section>
    <div class="container">
        <div class="columns">
            {% block conteudo %}

            {% endblock conteudo %}
        </div>
    </div>
</body>
</html>

message/templates/message/dashboard.html
{% extends 'base.html' %}

{% block conteudo %}
    <div class="column">
        {% for menssagem in mensagens %}
            <div class="box">
                {{ menssagem.body }}
                <span class="is-small has-text-grey-light">
                    ({{ menssagem.created_at }}) por {{ menssagem.user.username }}
                </span>
            </div>
        {% endfor %}
    </div>
    
    <div class="column is-one-third">
    
        <div class="block">
            <a href="{% url 'message:profile_list' %}">
                <button class="button is-dark is-outlined is-fullwidth">
                    Todos os perfis
                </button>
            </a>
        </div>
        <div class="block">
            <a href="{% url 'message:profile' user.profile.id %}">
                <button class="button is-success is-light is-outlined is-fullwidth">
                    Meu perfil
                </button>
            </a>
        </div>
        
        <div class="block">
            <div class="block">
                <p class="title is-2">Publicar pensamento</p>
            </div>
            <div class="block">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="button is-success is-fullwidth is-medium mt-5" type="submit">
                        Publicar
                    </button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

message/templates/message/profile.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="column">

    <div class="block">
        <h1 class="title is-1">
            Mensagens de {{profile.usuario.username|upper}}
        </h1>
        <form method="POST">
            {% csrf_token %}
            <div class="buttons has-addons">
                {% if profile in user.profile.seguidores.all %}
                    <button class="button is-success is-static">Follow</button>
                    <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
                {% else %}
                    <button class="button is-success" name="follow" value="follow">Follow</button>
                    <button class="button is-danger is-static">Unfollow</button>
                {% endif %}
            </div>
        </form>
    </div>
    <div class="content">
        {% for mensagem in profile.usuario.mensagens.all %}
            <div class="box">
                {{ mensagem.body }}
            </div>
            <span class="is-small has-text-grey-light">
                ({{ mensagem.created_at }})
            </span>
        {% endfor %}
    </div>
</div>


<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'message:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                Todos os perfis
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.usuario.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.seguidores.all %}
                <li>
                    <a href="{% url 'message:profile' following.id%}" >
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.usuario.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.seguido_por.all %}
                <li>
                    <a href="{% url 'message:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock %}

message/templates/message/profile_list.html
{% extends 'base.html' %}

{% block conteudo %}
<div class="column">

{% for profile in profiles  %}

    <div class="block">
        <div class="card">
            <a href="{% url 'message:profile' profile.id %}">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="https://bulma.io/images/placeholders/96x96.png" alt="">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">
                                {{ profile.usuario.username }}
                            </p>
                            <p class="subtitle is-6">
                                @{{ profile.usuario.username|lower }}
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

{% endfor %}

</div>

{% endblock conteudo %}